"""Add colunn email_submitted

Revision ID: 2944fac52f18
Revises: 17ff13aef599
Create Date: 2014-06-05 12:37:06.607458

"""

# revision identifiers, used by Alembic.
revision = '2944fac52f18'
down_revision = '17ff13aef599'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('email_submitted', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'email_submitted')
    ### end Alembic commands ###
