"""empty message

Revision ID: 5079f75e8510
Revises: 21aa259bef1d
Create Date: 2014-03-13 10:46:09.631319

"""

# revision identifiers, used by Alembic.
revision = '5079f75e8510'
down_revision = '21aa259bef1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('date_mark_to_checkout', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'date_mark_to_checkout')
    ### end Alembic commands ###
