"""empty message

Revision ID: 6051db11f4b
Revises: 1c4517136814
Create Date: 2014-03-13 10:25:02.052272

"""

# revision identifiers, used by Alembic.
revision = '6051db11f4b'
down_revision = '1c4517136814'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('user_mark_to_checkout', sa.VARCHAR(), nullable=True, default=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'user_mark_to_checkout')
    ### end Alembic commands ###
